apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-controller-manager
  namespace: {{ include "resource.default.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:{{ .Values.ports.proxy }}
        - --upstream=http://127.0.0.1:{{ .Values.ports.metrics }}/
        - --logtostderr=true
        - --v=10
        image: "{{ .Values.image.registry }}/{{ .Values.image.proxy.name }}:{{ .Values.image.proxy.tag }}"
        imagePullPolicy: {{ .Values.image.proxy.pullPolicy }}
        name: kube-rbac-proxy
        ports:
        - containerPort: {{ .Values.ports.proxy }}
          name: https
      - args:
        - --metrics-addr=127.0.0.1:{{ .Values.ports.metrics }}
        - --enable-leader-election=false
        image: "{{ .Values.image.registry }}/{{ .Values.image.controller.name }}:{{ .Values.image.controller.tag }}"
        imagePullPolicy: {{ .Values.image.controller.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: {{ .Values.ports.healthz }}
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        volumeMounts:
        - name: bootstrap-credentials
          mountPath: /etc/capv
          readOnly: true
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ include "resource.default.name" . }}
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: bootstrap-credentials
        secret:
          defaultMode: 420
          secretName: {{ include "resource.default.name" . }}-manager-bootstrap-credentials
