apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  name: {{ include "resource.metrics.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.ports.metrics }}
    targetPort: metrics
  selector:
    {{- include "labels.selector" . | nindent 4 }}
