apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-manager-bootstrap-credentials
  namespace: {{ include "resource.default.namespace" . }}
stringData:
  credentials.yaml: |-
    {{- if .Values.Installation.V1.Secret.CAPI.VMware }}
    username: {{ .Values.Installation.V1.Secret.CAPI.VMware.Username | quote }}
    password: {{ .Values.Installation.V1.Secret.CAPI.VMware.Password | quote }}
    {{- end }}
type: Opaque
