apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
stringData:
  credentials.yaml: |-
    username: {{ .Values.Installation.V1.Secret.Provider.VSphere.Username | quote }}
    password: {{ .Values.Installation.V1.Secret.Provider.VSphere.Password | quote }}
type: Opaque
