apiVersion: v1
data:
  password: '{{ (((((.Values.Installation).V1).Secret).Provider).VSphere).Password
    | b64enc }}'
  username: '{{ (((((.Values.Installation).V1).Secret).Provider).VSphere).Username
    | b64enc }}'
kind: Secret
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}'
  name: capv-credentials
  namespace: '{{ .Release.Namespace }}'
type: Opaque
