apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.cert.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: zzz-{{ include "resource.default.name" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.webhook.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-vsphereclustertemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vsphereclustertemplate.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - vsphereclustertemplates
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.webhook.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-vspherefailuredomain
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspherefailuredomain.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspherefailuredomains
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.webhook.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-vspheremachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspheremachine.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspheremachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.webhook.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-vspheremachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspheremachinetemplate.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspheremachinetemplates
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.webhook.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-vspherevm
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspherevm.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspherevms
  sideEffects: None
