apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-cert
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-validating-webhook-configuration
  namespace: {{ include "resource.default.namespace" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-vspherecluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspherecluster.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - vsphereclusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-vspheremachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspheremachine.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspheremachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-vspheremachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspheremachinetemplate.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspheremachinetemplates
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha4-vspherevm
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspherevm.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspherevms
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-vspherecluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspherecluster.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - vsphereclusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-vspheremachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspheremachine.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspheremachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-vspheremachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspheremachinetemplate.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspheremachinetemplates
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-vspherevm
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vspherevm.infrastructure.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspherevms
  sideEffects: None
