apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
  name: {{ include "resource.default.name" . }}-webhook
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: infrastructure-vsphere
