apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.webhook.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: webhook
  selector:
    {{- include "labels.selector" . | nindent 4 }}
