apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: '{{ .Release.Namespace }}'

resources:
  - input/infrastructure-components.yaml
  - patches/sa.yaml

transformers:
  - patches/common-labels.yaml

patchesStrategicMerge:
  - patches/delete-namespace.yaml
  - patches/delete-bootstrap-credentials-secret.yaml
  - patches/certificate.yaml
  - patches/webhook-certificate.yaml
  - patches/delete-issuer.yaml
  - patches/deployment-resources.yaml
  - patches/cluster-role-binding.yaml
  - patches/role-binding.yaml

patches:
  - path: patches/crd_cainjection.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-vsphere
  - path: patches/crd_webhook.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-vsphere
  - patch: |-
      - op: remove
        path: /spec/template/spec/volumes/1
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/1
    target:
      group: apps
      version: v1
      kind: Deployment
      name: capv-controller-manager
