namespace: "{{ .Release.Namespace }}"

resources:
  - patches/sa.yaml
  - patches/cluster-identity.yaml
  - input/infrastructure-components.yaml

transformers:
  - patches/common-labels.yaml
  - patches/monitoring-annotations.yaml

patchesStrategicMerge:
  - patches/delete-namespace.yaml
  - patches/certificate.yaml
  - patches/webhook-certificate.yaml
  - patches/delete-issuer.yaml
  - patches/deployment-resources.yaml
  - patches/cluster-role-binding.yaml
  - patches/role-binding.yaml
  - patches/secret.yaml

patches:
  - path: patches/crd_cainjection.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-vsphere
  - path: patches/crd_webhook.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-vsphere
